var heading = document.getElementById('heading')
var para=document.getElementsByClassName('para')
var tags=document.getElementsByTagName('a')
var tags=document.querySelector('.para')
console.log(tags)